defaults:
  - base_config
  - override data: sms_slurm
  - override hydra/job_logging: custom
  - _self_

hydra:
  run:
    dir: ./output/${exp_id}
  output_subdir: train-${now:%Y-%m-%d_%H-%M-%S}-hydra

exp_id: context_aware_avclip_lora_mmaudio_medium_sms

model: medium_44k_sa
mini_train: False
example_train: False
avs_train: False
hybrid_music_train: False
sms_train: True
weights: weights/mmaudio_medium_44k.pth

log_text_interval: 20
log_extra_interval: 500
val_interval: 1000
eval_interval: 15_000
save_eval_interval: 15_000
save_weights_interval: 1_000
save_checkpoint_interval: 4_000
save_copy_iterations: []

num_workers: 8
batch_size: 4
eval_batch_size: 6 # per-GPU

num_iterations: 70_000
learning_rate: 1.0e-5
linear_warmup_steps: 2500

lr_schedule: step
lr_schedule_steps: [60_000, 65_000]
lr_schedule_gamma: 0.1

clip_grad_norm: 1.0
weight_decay: 1.0e-6

# increases ability to directly recognize semantics in the cond
null_text_condition_probability: 0.5

use_lora: True
